# Generated by Django 5.1.1 on 2024-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'deliverd'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=100),
        ),
    ]
