# Generated by Django 5.1.1 on 2024-09-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_remove_orderitem_price_alter_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_cost',
        ),
    ]
